### ISSUE TITLE
When are the nodeUpdates events used?

### ISSUE THREAD

**Issue by blois** [Quansight-Labs/jupyter-output-spec#10]
I don't quite understand when the node that is being rendered into will change- in JupyterLab isn't the node typically Widget.node? When does the node change for a widget rather than the widget get re-rendered?

**Comment by saulshanabrook** [comment]
If you clone the output, then you have another node being rendered. If you close that, then that node is removed.

The thought was to have those being run by *one* function, instead of two, so that you could synchronize views between the two nodes client side. 

Does that make sense?

**Comment by blois** [comment]
If the goal is to enable synchronization between views, is that something which could be done out of band of this API?

Often for these scenarios the Python code will generate a unique UUID which is passed to the client, for example ipywidgets use this. Then they can synchronize the views via comm channels, or the browser's BroadcastChannel, or the JS module could just have a static map of ID->rendered object.

**Comment by saulshanabrook** [comment]
> If the goal is to enable synchronization between views, is that something which could be done out of band of this API?

It *could* be but for views that are entirely client side, which don't use comms, this would be necessary if they want synced views. 

> or the JS module could just have a static map of ID->rendered object.

Yeah I guess they could maintain some global instead...

Do you think it's too cumbersome for authors to handle new nodes coming in?

We could write a higher order function that takes a function that doesn't handle node updates and transforms it into one that does, by creating independent renderers for each node.

**Comment by blois** [comment]
I think it complicates the simple case and may result in renderers which work properly when displayed in one location but then have odd failure cases when they are rendered in multiple places.

I think the 'must implement' part of the API should be really minimal and ideally self-explanatory. As it is right now I could easily see people skip this portion of the API.

I'm just starting to play around with a Jupyter Lab extension supporting this (my first extension, hooray!), and I can do something like:

```python
from IPython.display import DisplayObject
import base64

class ExtensibleModule(DisplayObject):
    _MIME_TYPE = 'application/vnd.jupyter.extensible.alpha+json'
    
    def __init__(self, module=None, url=None):
        if module and url:
            raise ValueError('Cannot specify both module and url')
        if not module and not url:
            raise ValueError('Must specify either module or url')
        if module:
            url = 'data:text/javascript;base64,' + base64.b64encode(module.encode('utf-8')).decode('utf-8') 
        self._url = url
    
    def _repr_mimebundle_(self, include=None, exclude=None):
        mime_bundle = {} 
        mime_bundle[ExtensibleModule._MIME_TYPE] = {'url': self._url}
        return mime_bundle
        
    def _repr_javascript_module_(self):
        return {'url': 'something'}
```

Then:
```python
ExtensibleModule(module='''
export function renderFunction(args) {
    const div = document.createElement('div');
    div.style.background = 'lime';
    div.textContent = 'passed';
    args.node.appendChild(div);
}
''')
```

**Comment by blois** [comment]
Here's what I was using to play around with it in JupyterLab: https://github.com/blois/js-module-renderer/blob/master/src/index.ts

I tried to encapsulate some of the functionality in a notebook for testing:
https://github.com/blois/js-module-renderer/blob/master/tests.ipynb

**Comment by saulshanabrook** [comment]
> I think the 'must implement' part of the API should be really minimal and ideally self-explanatory. As it is right now I could easily see people skip this portion of the API.

That's a good point. Maybe we could somehow make it opt in, like we did for the `waitFor` thing?

How about this? https://github.com/Quansight-Labs/jupyter-output-spec/commit/ce538136c585eaae3f057e388a82c313691833c0 Therefore if you don't call the function, you will just get re-rendered for every output/node combination. If you do call the functions, you can handle those updates yourself as you see fit, for more control.


> I'm just starting to play around with a Jupyter Lab extension supporting this (my first extension, hooray!)

 🎉 🎊 🥳

@blois I like the trick of base64 encoding the module :) That's pretty nice way to iterate without having to deploy it at a URL!

Curious why you added the data was an object with a URL key instead of just a URL? Also good point about putting the version in the mimetype, just added that:https://github.com/Quansight-Labs/jupyter-output-spec/commit/06126bf24a730f12836fec15d93d892e005a31c3
