### ISSUE TITLE
Pass DisplayData as the Data object

### ISSUE THREAD

**Issue by blois** [Quansight-Labs/jupyter-output-spec#6]
Rather than:

```typescript
type RenderFn<T extends object> = (options: {
    // the actual mime data
    data: T,
}
```

I'd propose:

```typescript
// https://nbformat.readthedocs.io/en/latest/format_description.html#display-data
interface DisplayData {
  output_type: 'display_data';
  data: {[key: string]: any};
  metadata: {[key: string]: any};
}

type RenderFn= (options: {
    // the actual mime data
    data: DisplayData,
}
```

I was thinking about https://github.com/Quansight-Labs/jupyter-output-spec/issues/2#issuecomment-607372258, and passing the entire DisplayData object allows specifying the raw data in one entry of the DisplayData then allowing this renderer to access it. For example the data could reside in the mime type of a built-in renderer, but if that renderer isn't present then a JS module renderer could still access the data.

**Comment by saulshanabrook** [comment]
> For example the data could reside in the mime type of a built-in renderer, but if that renderer isn't present then a JS module renderer could still access the data.

Ah I like that!

I think then we could remove the `data` from the mimetype itself, so it would just be the url. So the mimebundle you output might look like:

```json
{
   'application/vnd.jupyter.extensible': 'http://some-url.com/a.js'
   'another-mimetype': 'some-data-for-that-mimetype'
}
```

Should we include the `output_type`? Will it always be `display_data`? Is it useful for the plugin?

---

We could then also make it possible to edit the display data in the renderer? This could be useful to add more mimetypes and save state, with the roundabout way I suggested in https://github.com/Quansight-Labs/jupyter-output-spec/issues/2#issuecomment-607365495

**Comment by blois** [comment]
I sort of like the object just because it seems more future-proof, but there's always the metadata for additional properties.

The output could probably also be an execute_result:
https://nbformat.readthedocs.io/en/latest/format_description.html#execute-result
