### ISSUE TITLE
DataUpdates should have promises

### ISSUE THREAD

**Issue by blois** [Quansight-Labs/jupyter-output-spec#7]
Currently the API has:

```typescript
type RenderFn<T extends object> = (options: {
    /// any updates of the data from update display
    dataUpdates: AsyncIterable<T>,
}) => AsyncIterable<{data: T, node: Element}>
```

And I think the AsyncIterable return type should really be encapsulated in the dataUpdates stream. The reason here is that you want to be able to have a concrete signal that the update completed. With the AsyncIterable there is no correlation between the update and the iterable result.

An example of an alternative would be the browser's FetchEvent: https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent with it's `waitUntil` method.

```typescript
interface UpdateDataDataEvent {
  data: DisplayData;
  waitUntil(promise: Promise<void>): void;
}

type RenderFn<T extends object> = (options: {
  dataUpdates: AsyncIterable<UpdateDataDataEvent>,
};
```

**Comment by saulshanabrook** [comment]
Ah I see, so as a consumer you pass a promise in that triggers when it's done rendering, nice!

How would that compare to just having a function you call when it's done, like this:

```typescript
interface UpdateDataDataEvent {
  data: DisplayData;
  broadcastDone(): void;
}

type RenderFn<T extends object> = (options: {
  dataUpdates: AsyncIterable<UpdateDataDataEvent>,
};
```

**Comment by blois** [comment]
I think the difference is that you have to provide the promise synchronously which will tell the source of the event to wait for the promise to resolve. If you do not set the promise immediately then the source can assume that the processing was done synchronously.

The broadcastDone() would either be required to be called always (which is a bit awkward), or you'd need a waitForDone() then broadcastDone() pair to let the source know to wait for the done to be called.

**Comment by saulshanabrook** [comment]
> The broadcastDone() would either be required to be called always (which is a bit awkward)

Yeah I was assuming we would require it, but I see what you mean. Assume that by default it will done synchronously, and if not then you must pass in a promise.
