### ISSUE TITLE
Comm API should handle Buffers

### ISSUE THREAD

**Issue by blois** [Quansight-Labs/jupyter-output-spec#8]
A number of widgets use the Buffers for transferring large chunks of raw data, this should be supported by the Comms APIs.

For this, the object being passed could be a bit more structured:

```typescript
interface CommMessage {
    readonly data: {[key: string]: any};
    readonly buffers?: ArrayBuffer[];
}

interface Comm {
  send(data: CommMessage): Promise<void>;
  close(): Promise<void>;
  // Iterator ends on close
  readonly msgs: AsyncIterable<CommMessage>;
}
```

**Comment by saulshanabrook** [comment]
> A number of widgets use the Buffers for transferring large chunks of raw data, this should be supported by the Comms APIs.

Oh interesting. I didn't know there were buffers. That's useful!

Here is a post from @jasongrout describing them I found: https://github.com/jupyter-widgets/ipywidgets/issues/2378#issuecomment-483345329

Are they documented anywhere in the notebook networking spec?

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/587#issuecomment-517403803.

Colab doesn't support them yet but this is on my list of things that I'd like to get working very soon.

**Comment by saulshanabrook** [comment]
Ah yeah here it is in ipykernel, to send messages with buffers: 

https://github.com/ipython/ipykernel/blob/ff122dd62388af07354cc209387dfa271294e8ee/ipykernel/comm/comm.py#L61-L72

**Comment by jasongrout** [comment]
Saul, they are part of the kernel message spec.

**Comment by saulshanabrook** [comment]
@jasongrout Yep! I see them now. They just aren't mentioned in the Jupyter Notebook comms docs, which is what I usually refer to https://jupyter-notebook.readthedocs.io/en/stable/comms.html
